# Generated by Django 4.1.7 on 2023-03-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutSite',
            new_name='Project',
        ),
    ]
