# Generated by Django 4.1.7 on 2023-03-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_site', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
